import { v4 as uuidv4 } from 'uuid';
import { eq, sql } from 'drizzle-orm';
import { withTenantSchema } from '../../shared/db/tenant.js';
import { invoices, orders, orderItems, productVariants } from '../../shared/db/schema/tenant.js';
import { NotFoundError } from '../../shared/errors/types.js';
import { documentsQueue } from '../../shared/queue/client.js';

export interface GenerateInvoiceJobData {
  tenantId: string;
  schemaName: string;
  invoiceId: string;
  orderId: string;
}

export async function generateInvoice(
  schemaName: string,
  tenantId: string,
  orderId: string,
) {
  return withTenantSchema(schemaName, async (db) => {
    const [order] = await db
      .select()
      .from(orders)
      .where(eq(orders.id, orderId))
      .limit(1);
    if (!order) throw new NotFoundError('Order', orderId);

    // Sequential invoice number
    const [row] = await db.select({ count: sql<string>`count(*)` }).from(invoices);
    const nextNum = parseInt(row?.count ?? '0') + 1;
    const invoiceNumber = `INV-${String(nextNum).padStart(6, '0')}`;

    const invoiceId = uuidv4();
    await db.insert(invoices).values({
      id: invoiceId,
      orderId,
      invoiceNumber,
      status: 'draft',
    });

    // Enqueue PDF generation (non-blocking — PDF is generated by a BullMQ worker)
    await documentsQueue.add('generate-invoice-pdf', {
      tenantId,
      schemaName,
      invoiceId,
      orderId,
    } satisfies GenerateInvoiceJobData);

    const [invoice] = await db.select().from(invoices).where(eq(invoices.id, invoiceId));
    return invoice!;
  });
}

export async function getInvoice(schemaName: string, invoiceId: string) {
  return withTenantSchema(schemaName, async (db) => {
    const [invoice] = await db
      .select()
      .from(invoices)
      .where(eq(invoices.id, invoiceId))
      .limit(1);
    if (!invoice) throw new NotFoundError('Invoice', invoiceId);

    // Attach order + line items for rendering
    if (invoice.orderId) {
      const [order] = await db
        .select()
        .from(orders)
        .where(eq(orders.id, invoice.orderId))
        .limit(1);

      const items = await db
        .select({
          id: orderItems.id,
          variantId: orderItems.variantId,
          variantName: productVariants.name,
          sku: productVariants.sku,
          quantity: orderItems.quantity,
          unitPriceKobo: orderItems.unitPriceKobo,
          discountKobo: orderItems.discountKobo,
          taxKobo: orderItems.taxKobo,
          lineTotalKobo: orderItems.lineTotalKobo,
        })
        .from(orderItems)
        .innerJoin(productVariants, eq(orderItems.variantId, productVariants.id))
        .where(eq(orderItems.orderId, invoice.orderId));

      return { ...invoice, order, items };
    }

    return invoice;
  });
}

export async function listInvoices(schemaName: string, orderId?: string) {
  return withTenantSchema(schemaName, async (db) => {
    const where = orderId ? eq(invoices.orderId, orderId) : undefined;
    return db.select().from(invoices).where(where);
  });
}
